# Generated by Django 3.2.9 on 2021-11-16 17:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_one', '0003_auto_20211116_1750'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AccessRecord',
        ),
    ]
