# Generated by Django 3.2.9 on 2021-11-16 18:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_one', '0005_accessrecord'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AccessRecord',
        ),
    ]
